coverage_clover: build/logs/clover.xml
repo_token: 4621be82c391b15ab9416b68655ea39cd09e95f1

service_name: travis-ci # travis-ci or travis-pro

# for php-coveralls
coverage_clover: build/logs/clover.xml
json_path: build/logs/coveralls-upload.json